### ISSUE TITLE
favicon関連

### ISSUE THREAD

**Issue by YasunoriMATSUOKA** [lcnem/website#31]
@KimuraYu45z 
faviconが非表示になっている。(スクショの赤枠の箇所)
![image](https://user-images.githubusercontent.com/55148923/99049808-a36f2300-25da-11eb-916f-cebfe632aa4c.png)

Press KitのPNG画像ダウンロードで以下の(スクショの赤枠の箇所の)PNGをクリックすると、favicon.pngのダウンロードができることが期待値だが、favicon.htmlというファイルがダウンロードされる。
![image](https://user-images.githubusercontent.com/55148923/99050114-0cef3180-25db-11eb-9548-a796bbbd1ad3.png)

**Comment by KimuraYu45z** [comment]
ありがとうございます！！
